version: '3.1'
services:
 app:
    container_name: spring-app
    image: spring-app
    build: ./iss
    ports:
      - "8080:8080"
    depends_on:
    - db
    - angularapp
 db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=treinamento
 angularapp:
    container_name: angular-app
    image: angular-app
    build: ./avaliacao
    ports: 
      - "80:80"